### PR TITLE
Fix breaking change from algebra/poly

### PR DESCRIPTION
**Pull request by Cesar199999**
Introduced by https://github.com/arkworks-rs/algebra/pull/843

### CODE REVIEW

**Comment by mmagician** [comment]
@Cesar199999 @Antonio95 wait shouldn't we wait for the arkworks PR to get merged?

**Comment by Antonio95** [comment]
Who knows when that will happen, right? This is a change we want to use in Aurora and I think dependencies could be annoying if we leave this in a non-main branch (perhaps that would involve changing the algebra dependency in our HCS repos that depend on `HCS/algebra` which we use in `Aurora`? Or does that get handled automatically if you only patch Aurora; what I mean is: A depends on B and C, and B depends on C; do A and B have to point to the same branch of C?).

If you prefer us to keep the branch here and point to it, and restore main to its state before the merge, just let us know

**Comment by Cesar199999** [comment]
I agree @Antonio95, this is the easiest way to deal with the dependencies, but we undo it if you prefer.
Also, even if we rollback the changes from `algebra`, this won't be a problem as we are just writing the reference explicitly.

**Comment by Antonio95** [comment]
Oh yep, maybe that's an important point which wasn't clear: the tiny change we added here works with both the new (to-be-merged) and the old (current `main`) `algebra`; whereas the previous code only worked with the old `algebra`.

**Comment by mmagician** [comment]
what I mean is: we don't even depend on our fork of algebra where this is supposed to be introduced?

**Comment by mmagician** [comment]
> Oh yep, maybe that's an important point which wasn't clear: the tiny change we added here works with both the new (to-be-merged) and the old (current main) algebra; whereas the previous code only worked with the old algebra.

Ah, I see, so this change is forward compatible? then all good

**Comment by Antonio95** [comment]
Yes, this change is everything-compatible :)

**Pull request merged**
